const SAIGON_MENU=[
  {category:'Закуски',items:[['Нем',550,'250 г'],['Нем Том',650,'250 г'],['Нем Хайсан',690,'250 г'],['Нем Куон',680,'250 г'],['Димсам',650,'250 г'],['Дау',550,'200 г'],['Бань Бао',300,''],['Батат Фри',500,''],['Ассорти Немов',890,''],['Курица по-сайгонски',580,''],['Креветки Темпура',650,''],['Креветки по-сайгонски',680,''],['Креветки на гриле',680,'']]},
  {category:'Лапша',items:[['Бун Бо',700,'600 г'],['Бун Ча',700,'600 г'],['Фо Чон Вит',730,'600 г'],['Ми Том Ям',750,'500 г'],['Ми Сао (говядина)',700,'500 г'],['Ми Сао (курица)',650,'500 г'],['Ми Сао (морепродукты)',750,'500 г'],['Миен Сао (говядина)',680,'500 г'],['Миен Сао (курица)',620,'500 г'],['Миен Сао (морепродукты)',720,'500 г']]},
  {category:'Рис',items:[['Ком Бо Бит Тет',700,'350 г'],['Ком Га по-сайгонски',650,'350 г'],['Ком Вит Сот',730,'350 г'],['Ком Том Сот',730,'350 г']]},
  {category:'Суп',items:[['Том Ям',630,'700 г'],['Фо Вит',700,'700 г'],['Бун Хайсан',650,'700 г'],['Фо Бо',550,'700 г'],['Фо Тайлан',650,'700 г'],['Фо Га',550,'700 г']]},
  {category:'Десерт',items:[['Манго Саго',450,''],['Соевый пуддинг с тапиокой',300,''],['Моти (в ассортименте)',250,''],['Мороженое (в ассортименте)',350,'']]},
  {category:'Салат',items:[['Ном Бо',600,'300 г'],['Ном Хоай',650,'300 г'],['Салат Бо',650,'300 г']]}
];
const FEATURED_DISHES=[
  {name:'Фо Бо',category:'Суп',price:550,weight:'700 г',note:'Большая порция вьетнамской классики',className:'featured-pho',badge:'Классика',image:'assets/menu/pho-bo.webp',ingredients:'Рисовая лапша, говядина, ароматный говяжий бульон, лук, свежая зелень и лайм.'},
  {name:'Том Ям',category:'Суп',price:630,weight:'700 г',note:'Яркий, пряный и насыщенный',className:'featured-tom',badge:'Яркий вкус',image:'assets/menu/tom-yam.webp',ingredients:'Креветки, грибы, пряный бульон том ям, кокосовая основа, лемонграсс, лайм, чили и свежая зелень.'},
  {name:'Бун Ча',category:'Лапша',price:700,weight:'600 г',note:'Один из самых узнаваемых вкусов Вьетнама',className:'featured-bun',badge:'Стоит попробовать',image:'assets/menu/bun-cha.webp',ingredients:'Рисовая лапша бун, свинина на гриле, свежая зелень, овощи и кисло-сладкий соус.'},
  {name:'Нем Хайсан',category:'Закуски',price:690,weight:'250 г',note:'Хрустящая закуска с морепродуктами',className:'featured-nem',badge:'Для компании',image:'assets/menu/nem-haisan.webp',ingredients:'Хрустящие роллы с морепродуктами и овощной начинкой, свежая зелень и соус для подачи.'},
  {name:'Ком Том Сот',category:'Рис',price:730,weight:'350 г',note:'Креветки, рис и насыщенный соус',className:'featured-rice',badge:'Основное',image:'assets/menu/com-tom-sot.webp',ingredients:'Рис, креветки, овощи, зелёный лук и соус в азиатском стиле.'}
];
const menuSection=document.querySelector('.menu-section');
if(menuSection){
  const shell=menuSection.querySelector('.shell');
  const total=SAIGON_MENU.reduce((sum,group)=>sum+group.items.length,0);
  shell.innerHTML=`<div class="section-head menu-heading"><div><p class="eyebrow">Что заказать</p><h2 id="menu-title">Начните с самого интересного</h2></div><a class="text-link" href="https://yandex.ru/maps/org/saygon/105448387404/menu/?ll=37.867304%2C55.917370&z=17" target="_blank" rel="noopener">Сверить меню на Яндекс Картах →</a></div><p class="section-intro menu-intro">Тапните по блюду — увидите основные ингредиенты и живой пар. Полное меню со всеми ${total} позициями раскрывается ниже.</p><div class="featured-menu" aria-label="Рекомендуемые блюда">${FEATURED_DISHES.map((dish,index)=>`<article class="featured-dish ${dish.className}${index===0?' featured-dish-main':''}" role="button" tabindex="0" aria-expanded="false" aria-label="${dish.name}: показать ингредиенты"><img class="featured-dish-image" src="${dish.image}" alt="${dish.name} — блюдо Saigon VN" loading="${index===0?'eager':'lazy'}" decoding="async"><div class="featured-dish-shade"></div><div class="card-steam" aria-hidden="true"><i></i><i></i><i></i></div><div class="featured-dish-content"><div class="featured-topline"><span>${dish.badge}</span><span>${dish.category}</span></div><div class="featured-summary"><h3>${dish.name}</h3><p>${dish.note}</p><div class="featured-price"><strong>${dish.price.toLocaleString('ru-RU')} ₽</strong>${dish.weight?`<span>${dish.weight}</span>`:''}</div><span class="featured-tap-hint">Тапните, чтобы раскрыть состав</span></div></div><div class="featured-details" aria-hidden="true"><button class="featured-close" type="button" aria-label="Закрыть состав">×</button><span class="featured-details-kicker">Основные ингредиенты</span><h4>${dish.name}</h4><p>${dish.ingredients}</p><small>Точный состав, способ приготовления и аллергены уточняйте у ресторана.</small></div></article>`).join('')}</div><div class="menu-expand-wrap"><button class="btn btn-primary menu-expand" type="button" aria-expanded="false" aria-controls="full-menu">Показать всё меню <span>${total} позиций</span></button><p>Закуски, лапша, рис, супы, десерты и салаты — с актуальными ценами и граммовками.</p></div><div class="full-menu" id="full-menu" hidden><div class="menu-meta"><span>${total} позиций</span><span>${SAIGON_MENU.length} категорий</span><span>цены в ₽</span></div><div class="menu-catalog" data-menu-root></div><div class="menu-source"><p><strong>Источник меню:</strong> карточка Saigon VN на Яндекс Картах. Если ресторан обновит цены раньше сайта, ориентируйтесь на карточку Яндекса.</p><a class="btn btn-ghost" href="https://yandex.ru/maps/org/saygon/105448387404/menu/?ll=37.867304%2C55.917370&z=17" target="_blank" rel="noopener">Открыть оригинал</a></div></div>`;
  const featuredCards=[...shell.querySelectorAll('.featured-dish')];
  const setCardState=(card,open)=>{card.classList.toggle('is-active',open);card.setAttribute('aria-expanded',String(open));const details=card.querySelector('.featured-details');if(details)details.setAttribute('aria-hidden',String(!open))};
  const closeAllCards=()=>featuredCards.forEach(card=>setCardState(card,false));
  const toggleCard=(card)=>{const open=!card.classList.contains('is-active');closeAllCards();setCardState(card,open)};
  featuredCards.forEach(card=>{card.addEventListener('click',event=>{if(event.target.closest('.featured-close')){event.stopPropagation();setCardState(card,false);card.focus();return}toggleCard(card)});card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleCard(card)}if(event.key==='Escape'){event.preventDefault();setCardState(card,false)}})});
  document.addEventListener('pointerdown',event=>{if(!event.target.closest('.featured-dish'))closeAllCards()});
  const expandButton=shell.querySelector('.menu-expand'),fullMenu=shell.querySelector('#full-menu');
  expandButton.addEventListener('click',()=>{const opening=fullMenu.hidden;fullMenu.hidden=!opening;expandButton.setAttribute('aria-expanded',String(opening));expandButton.innerHTML=opening?'Скрыть полное меню':'Показать всё меню <span>'+total+' позиций</span>';if(opening){requestAnimationFrame(()=>fullMenu.classList.add('open'));setTimeout(()=>fullMenu.scrollIntoView({behavior:'smooth',block:'start'}),80)}else{fullMenu.classList.remove('open');expandButton.focus()}});
  const menuRoot=shell.querySelector('[data-menu-root]'),tabs=document.createElement('div'),panels=document.createElement('div');tabs.className='menu-tabs';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Категории полного меню');panels.className='menu-panels';
  const activate=(targetTab,targetPanel,focus=false)=>{tabs.querySelectorAll('.menu-tab').forEach(tab=>{const active=tab===targetTab;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1});panels.querySelectorAll('.menu-panel').forEach(panel=>{const active=panel===targetPanel;panel.classList.toggle('active',active);panel.hidden=!active});if(focus){targetTab.focus({preventScroll:true});targetTab.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}};
  SAIGON_MENU.forEach((group,index)=>{const tabId=`menu-tab-${index}`,panelId=`menu-panel-${index}`;const tab=document.createElement('button');tab.type='button';tab.id=tabId;tab.className=`menu-tab${index===0?' active':''}`;tab.textContent=group.category;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(index===0));tab.setAttribute('aria-controls',panelId);tab.tabIndex=index===0?0:-1;const panel=document.createElement('section');panel.className=`menu-panel${index===0?' active':''}`;panel.id=panelId;panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',tabId);panel.hidden=index!==0;panel.innerHTML=`<div class="menu-panel-head"><p>${group.category}</p><span>${group.items.length} позиций</span></div><div class="menu-list">${group.items.map(([name,price,weight])=>`<article class="menu-item"><div><h3>${name}</h3>${weight?`<p>${weight}</p>`:''}</div><strong>${price.toLocaleString('ru-RU')} ₽</strong></article>`).join('')}</div>`;tab.addEventListener('click',()=>activate(tab,panel));tabs.appendChild(tab);panels.appendChild(panel)});
  tabs.addEventListener('keydown',event=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const allTabs=[...tabs.querySelectorAll('.menu-tab')];const current=allTabs.indexOf(document.activeElement);let next=current<0?0:current;if(event.key==='ArrowRight')next=(next+1)%allTabs.length;if(event.key==='ArrowLeft')next=(next-1+allTabs.length)%allTabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=allTabs.length-1;const nextTab=allTabs[next],nextPanel=panels.querySelector(`#${nextTab.getAttribute('aria-controls')}`);activate(nextTab,nextPanel,true)});
  menuRoot.replaceChildren(tabs,panels);
}
